backend/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'backend'
urlpatterns = [
    path('index.html', views.index, name='index'),
    path('article-<int:tags__nid>-<int:category_id>.html', views.article, name='article'),
    path('edit-article-<int:nid>.html', views.edit_article, name='edit_article'),
    path('add-article.html', views.add_article, name='add_article'),
    path('del-article.html', views.del_article, name='del_article'),
    path('category.html', views.category, name='category'),
    path('del-category.html', views.del_category, name='del_category'),
    path('add-category.html', views.add_category, name='add_category'),
    path('tag.html', views.tag, name='tag'),
    path('del-tag.html', views.del_tag, name='del_tag'),
    path('add-tag.html', views.add_tag, name='add_tag'),
    path('base-info.html', views.base_info, name='base_info'),
    path('upload', views.upload),
    path('upload-avatar.html', views.upload_avatar),
]

blog/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    re_path(r'^blog/(\w+)/(tag|category|archive)/(.+).html$', views.home),
    re_path(r'^blog/(\w+).html$', views.home, name='home'),
    re_path(r'^blog/(\w+)/article/(\d+).html$', views.get_article_detail, name='article_detail'),
    path('blog/up_down/', views.up_down),
    path('blog/comment/', views.comment),
    path('', views.index, name='index'),

]

mybbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.views import serve
# from django.conf import settings
from mybbs import settings
from django.conf.urls.static import static
from django.conf import urls
from django.views import static as views_static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    # path('favicon.ico', RedirectView.as_view(url='static/img/favicon.ico')),
    path('backend/', include('backend.urls', namespace='backend')),
    path('favicon.ico', serve, {'path': 'img/favicon.ico'}),
    # path('media/<path:par>',  serve, {'document_root': MEDIA_ROOT}),
    # re_path(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': MEDIA_ROOT}),
    path('', include('blog.urls', namespace='blog')),
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', views_static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', views_static.serve,
        {'document_root': settings.MEDIA_ROOT}, name='media'),

]
if os.getcwd() != '/app':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG is True:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('check_username_exist/', views.check_username_exist, name='check_username_exist'),
    path('get_valid_img/', views.get_valid_img, name='get_valid_img'),
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
class UserInfo(AbstractUser):
    """..."""
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog", to_field="nid", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

class Blog(models.Model):
    """博客信息"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64) #个人博客标题
    site = models.CharField(max_length=32, unique=True) #个人博客后缀
    theme = models.CharField(max_length=32) #博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name

class Category(models.Model):
    """个人博客文章分类"""
    nid =  models.AutoField(primary_key=True)
    title = models.CharField(max_length=32) #分类标题
    blog = models.ForeignKey(Blog, to_field="nid", on_delete=models.CASCADE) #外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        unique_together = (("title", "blog"),)
        verbose_name_plural = verbose_name

class Tag(models.Model):
    """标签"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32) #标签名
    blog = models.ForeignKey(to="Blog", to_field="nid", on_delete=models.CASCADE) #所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        unique_together = (("title", "blog"),)
        verbose_name_plural = verbose_name

class Article(models.Model):
    """文章"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题") #文章标题
    desc = models.CharField(max_length=250, null=True)  # 文章描述
    create_time = models.DateTimeField(auto_now_add=True) #创建时间

    #评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    #点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)

    #踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)

    category = models.ForeignKey(to="Category", to_field="nid", on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    tags = models.ManyToManyField(#中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"), #注意顺序!!!
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural =verbose_name

class ArticleDetail(models.Model):
    """文章详情表"""
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(Article, to_field="nid", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """文章给和标签的多对多关系表"""
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid", on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid", on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}".format(self.article.title, self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name

class ArticleUpDown(models.Model):
    """点赞表"""
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """评论表"""
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid", on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    content = models.CharField(max_length=255) #评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE) #blank=True 在django的admin中可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

users/forms.py
"""
users 中用到的form类
"""

from django import forms
from django.core.exceptions import ValidationError
from blog import models

#定义一个注册的form类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="用户名",
        error_messages={
            "max_length": "用户名最长16位",
            "required": "用户名不能为空",
        },
        widget=forms.widgets.TextInput(
            attrs={"class":"form-control"},
        )
    )

    password = forms.CharField(
        min_length=6,
        label="密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class":"form-control"},
            render_value=True, #form表单提交时，添加这个参数之后，当密码输入错误，重新返回的时候会显示之前填的密码
        ),
        error_messages={
            "min_length":"密码至少6位!",
            "required":"密码不能为空",
        }
    )
    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class":"form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length":"确认密码至少要6位!",
            "required": "确认密码不能为空"
        }
    )
    email = forms.EmailField(
        label="邮箱",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},
        ),
        error_messages={
            "invalid": "邮箱格式不正确！",
            "required": "邮箱不能为空",
        }
    )

    #重写username字段的局部钩子
    def clean_username(self):
        username=self.cleaned_data.get("username")
        isExist = models.UserInfo.objects.filter(username=username)
        if isExist:
            #表示用户名已注册
            self.add_error("username", ValidationError("用户名已存在"))
        else:
            return username

    #重写email字段的局部钩子
    def clean_email(self):
        email = self.cleaned_data.get("email")
        isExist = models.UserInfo.objects.filter(email=email)
        if isExist:
            #邮箱已注册
            self.add_error("email", ValidationError("邮箱已被注册"))
        else:
            return email


    #重写全局钩子
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))
        else:
            return self.cleaned_data

templates/backend_category.html
{% extends 'backend_layout.html' %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form method="POST" class="form-horizontal" action={% url 'backend:add_category' %}>
                {% csrf_token %}
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input required="required" type="text" class="form-control" id="nickname" name="cat_title"
                                   placeholder="请输入分类名称">
                        </div>
                        <div class="col-xs-3">
                            <input type="submit" class="btn btn-primary" value="添 加">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            分类列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th style="width: 30%">分类</th>
                <th style="width: 30%">文章个数</th>
                <th style="width: 40%">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for category in category_list %}
                <tr>
                    <td>{{ category.title }}</td>
                    <td style="display: none;">
                        <input nid={{ category.nid }} value={{ category.title }}>
                        <button class="confirm-edit" type="button"  aria-hidden="true" style="color: green">
                            &radic;
                        </button>
                         <button class="cancel-edit" type="button"  aria-hidden="true"  style="color: red">
                            &times;
                        </button>
                        <span class="error-edit" style="color: red"></span>
                    </td>
                    <td>{{ category.c }}</td>
                    <td>
                        <a class="btn btn-danger btn-xs"
                           data-href="/backend/del-category.html?title={{ category.title }}" data-toggle="modal"
                           data-target="#confirm-delete">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs edit-button">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
                {{ page_str }}
            </ul>
        </div>

        <!-- 模态框（Modal） -->
        <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h3 class="modal-title" id="myModalLabel">
                            <i class="fa fa-warning" aria-hidden="true"> 提示</i>
                        </h3>
                    </div>
                    <h4 class="modal-body col-md-offset-2">
                        你是否确认删除该分类？删除后无法恢复！！！
                    </h4>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                        </button>
                        <a type="button" data-dismiss="modal" class="btn btn-primary btn-ok">
                            确认
                        </a>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal -->
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>

        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'))
        });
        $('.btn-ok').click(function () {
            var url = $(this).attr('href');
            console.log(url)
            $.ajax({
                url: url,
                type: "get",
                success: function (data) {
                    if (data.status) {
                        alert(data.msg);
                    } else {
                        location.reload()
                    }
                }
            });
        });
        $('.edit-button').click(function () {
            $(this).parent().prev().prev().css('display','block').prev().css('display','none');
        })
        $('.cancel-edit').click(function () {
            $(this).parent().css('display','none').prev().css('display','block');
            $(this).next().text("")
        })
        $('.confirm-edit').click(function () {
            var title = $(this).prev().val();
            var nid = $(this).prev().attr('nid')
            $(this).addClass("commit_flag")
            $.ajax({
                url: "{% url 'backend:category' %}",
                type: "post",
                data: {"title": title,
                        "nid": nid,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (data) {
                    if (data.status) {
                        $(".commit_flag").next().next().text(data.msg)
                    } else {
                        $(".commit_flag").parent().css('display','none').prev().css('display','block');
                        $(".commit_flag").parent().css('display','none').prev().text(title);
                        $(".commit_flag").next().next().text("")
                        $(".commit_flag").removeClass('commit_flag');
                    }
                }
            });
        })

    </script>
{% endblock %}

templates/backend_edit_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content{
            width: 100%;
            min-height: 500px;
        }
        .error-info{
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">添加文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/backend/edit-article-{{ nid }}.html" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span class="error-info">{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span class="error-info">{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>分类 <span class="error-info">{{ form.category_id.errors.0 }}</span></label>

                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span class="error-info">{{ form.tags.errors.0 }}</span></label>

                <div>
                    {{ form.tags }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/kindeditor/lang/zh_CN.js"></script>
    <script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
    <script>
    KindEditor.ready(function (K) {
            window.editor = K.create('#kind-content', {
                    resizeType:2,
                    uploadJson:"upload",
                    extraFileUploadParams:{
                            csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    filePostName:"upload_img"
            });
        });
    </script>
{% endblock %}

templates/backend_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/static/css/backend.css"/>
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.css"/>
    {% block css %} {% endblock css %}
</head>
<body>
<div class="pg-header">
    <div class="logo left">
        <a href={% url "backend:index" %}>后台管理</a>
    </div>
    <div class="left left-menu">
        <a class="menu-item" href="/">博客首页</a>
    </div>
    <div class="right-menu right clearfix">
        <div class="user-info right">
            <a href="#" >
                <img class="img-circle avatar" src="/media/{{ request.user.avatar }}">
            </a>
            <div class="more-info">
                <a href="#" class="more-item">个人信息</a>
                <a href="{% url "users:logout" %}" class="more-item">注销</a>
            </div>
        </div>
        <div class="user-menu right">
            消息
            <i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
            <span class="badge">2</span>
        </div>
        <div class="user-menu right">
            任务
            <i class="glyphicon glyphicon-bell" aria-hidden="true"></i>
            <span class="badge">2</span>
        </div>
    </div>
</div>
<div class="pg-body">
    <div class="menu">
        <a class="menu-item" href="/backend/article-0-0.html">
            <i class="glyphicon glyphicon-wrench" aria-hidden="true"></i>
            <span>文章管理</span>
        </a>
        <a class="menu-item" href={% url 'backend:category' %}>
            <i class="glyphicon glyphicon-wrench" aria-hidden="true"></i>
            <span>分类管理</span>
        </a>
        <a class="menu-item" href={% url 'backend:tag' %}>
            <i class="glyphicon glyphicon-wrench" aria-hidden="true"></i>
            <span>标签管理</span>
        </a>
        <a class="menu-item" href={% url 'backend:base_info' %}>
            <i class="glyphicon glyphicon-wrench" aria-hidden="true"></i>
            <span>个人中心</span>
        </a>
    </div>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</div>
    <script type="text/javascript" src="/static/js/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎登录</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/users.css">
</head>
<body>
<div class="login">
    <div style="font-size: 25px; font-weight: bold; text-align: center;">
        用户登录
    </div>
    <form>
        {% csrf_token %}
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="密码">
        </div>
        <div class="form-group">
            <label for="valid_code">验证码</label>
                <div class="row">
                <div class="col-md-6">
                    <input type="text" class="form-control" name="valid_code" id="valid_code" placeholder="验证码">
                </div>
                <div class="col-md-3">
                    <img id="valid-img" class="valid-img" src="{% url 'users:get_valid_img' %}" alt="">
                </div>
            </div>
        </div>
        <div class="form-group">
            <lable>
                <input type="checkbox" value="1" name="valibleTime" id="valibleTime"> 一个月内自动登录
            </lable>
            <div class="right">
                <a href="#">忘记密码？</a>
            </div>
        </div>
        <div class="form-group">
            <div style="margin-top: 20px;">
                <button type="button" class="btn btn-default" id="login-button">登录</button>
                <span class="login-error"></span>
            </div>
        </div>
    </form>
</div>
<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    $("#login-button").click(function () {
        var formdata = new FormData();
        //1.获取用户填写的用户名和密码
        var username = $("#username").val();
        var password = $("#password").val();
        var valid_code = $("#valid_code").val();
        formdata.append("username", username);
        formdata.append("password", password);
        formdata.append("valid_code", valid_code);
        formdata.append("valibleTime", $("#valibleTime").is(":checked"));
        console.log($("#valibleTime").is(":checked"));
        formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        //2.使用ajax发送到服务端
        $.ajax({
            url: "{% url 'users:login' %}",
            type: "post",
            processData: false, //告诉jQuery不要处理我的数据
            contentType: false, //告诉jQuery不要设置content类型
            {#data: {#}
            {#    "username": username,#}
            {#    "password": password,#}
            {#    "valid_code": valid_code,#}
            {#"csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),#}
            {##}
            data: formdata,
            success: function (data) {
                if (data.status) {
                    //有错误，在页面上提示
                    $(".login-error").text(data.msg);
                } else {
                    //登录成功
                    location.href = data.msg;
                }
            }
        })
    });

    //当前input框获取焦点时将之前的错误清空
    $("#username, #password").focus(function () {
        $(".login-error").text("");
    });

    //点击图片，刷新验证码
    $("#valid-img").click(function () {
        $(this)[0].src += '?';
    })
</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/users.css">
    <style>
    </style>
</head>
<body>
<div class="register">
    <div style="font-size: 25px; font-weight: bold; text-align: center; padding: 20px 0px">
        用户注册
    </div>
{#form 中添加novalidate禁止使用浏览器进行输入合法性检查#}
    <div class="row">
        <div class="col-md-12 cxol-md-offset-0">
            <form novalidate autocomplete="off" action="/reg/" method="post" class="form-horizontal reg-form"
                  enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-3 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-7">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-3 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-7">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-3 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-7">
                        {{ form_obj.re_password }}
                        <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-3 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-7">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label
                            class="col-sm-3 control-label">头像</label>
                    <div class="col-sm-7">
                        <label for="id_avatar"><img id="avatar-img" src="/static/img/default.png" alt=""></label>
                        <input accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <button type="button" class="btn btn-success" id="reg-submit">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    //找到头像的input标签，绑定change事件
    $("#id_avatar").change(function () {
        // 1.创建一个读取文件的对象
        var fileReader = new FileReader();
        // 2.取到当前选中的头像文件
        {#console.log(this.files[0]);#}
        // 3.读取到选中的文件
        fileReader.readAsDataURL(this.files[0]);
        // 4.读取完之后，加载到img标签
        fileReader.onload = function () {
            $("#avatar-img").attr("src", fileReader.result);
            console.log(fileReader.result);
        }
    });

    //AJAX提交注册的数据
    $("#reg-submit").click(function () {
        //选取用户填写的注册数据，向后端发送AJAX请求
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("avatar", $("#id_avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            {#url: "/users/register/",#}
            url: "{% url 'users:register' %}",
            type: "post",
            processData: false, //告诉jQuery不要处理我的数据
            contentType: false, //告诉jQuery不要设置content类型
            data: formData,
            success: function (data) {
                {#console.log(data);#}
                if (data.status) {
                    //有错误就展示错误
                    //console.log(data.msg);
                    //将错误信息写到页面上
                    $.each(data.msg, function (k, v) {
                        //console.log("id_"+k, v[0]);
                        //concole.log($("#id_"+k));
                        $("#id_" + k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })
                } else {
                    //没有错误跳转到指定页面
                    location.href = data.msg;
                }
            }
        });
    });

    //将所有的input框绑定获取焦点的时间，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    });

    //给username input框绑定一个失去焦点的事件，失去焦点后自动校验用户名是否已经注册
    $("#id_username").on("input", function () {
        //获取到用户填写的值
        var username = $(this).val();
        //发送请求
        $.ajax({
            url: "{% url "users:check_username_exist" %}",
            type: "get",
            data: {"username": username},
            success: function (data) {
                if (data.status) {
                    //用户名已注册
                    $("#id_username").next().text(data.msg).parent().parent().addClass("has-error");
                } else {
                    $("#id_username").next().text(data.msg).parent().parent().removeClass("has-error");
                }
            }
        });
    });


</script>
</body>
</html>